#!/bin/bash

set -e

echo "🔄 更新软件源..."
apt update -y

echo "📦 安装常用工具..."
apt install -y \
    command-not-found \
    bash \
    wget \
    curl \
    passwd \
    tzdata \
    bc \
    jq \
    tar \
    zstd \
    xz-utils \
    zip \
    unzip \
    iptables \
    ufw \
    net-tools \
    openssl \
    dnsutils \
    libnss3 \
    socat \
    sqlite3 \
    iperf3

echo "✨ 安装完成！"
